---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nexzrpfa/valengrading.nexztech.com
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - php artisan config:clear
    - php artisan route:clear
